

site_name: Projeto de Software Ágil

theme:
  name: active-handout
  language: pt
  features:
    - navigation.tabs
    - header.autohide

docs_dir: content
site_dir: docs

site_url: https://gttonin.github.io/projetodesoftwareagil/
repo_name: "projetodesoftwareagil"

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/js-yaml/4.0.0/js-yaml.min.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/gh/insper-education/active-handout-plugins-js@v0.2.2/package/plugin-bundle.js

markdown_extensions:
  - toc:
      toc_depth: 0
  - markdown.extensions.admonition
  - meta
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: "content/"
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.critic:
      mode: view
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list
  - pymdownx.arithmatex:
      generic: true

plugins:
  - dev-environment
  - active-exercises:
      offering_id: 5
  - contributors
  - search

extra:
  ihandout_config:
    mount-point: /
    calendar: /calendar.yml
    counter:
      - question
      - tip
      - exercise
      - example


################################################
## PA                                 ##
################################################
nav:
  - Home:
      - index.md
  - Sobre a disciplina:
      - sobre/index.md
      - sobre/configuracao/index.md
      - Calendário: sobre/calendario/index.md
